name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: build and publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set environment
      run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "COMMIT_MSGS=$(git log --pretty=format:'- %s (@%an) (#%h)' "$(git describe --tags `git rev-list --tags --max-count=1`)..HEAD")" >> $GITHUB_ENV
          sudo apt install libx11-dev libnotify-dev
    - name: build
      run: make release

    - name: upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: keyboard-notify-x11
        asset_name: keyboard-notify-x11-${{ env.RELEASE_VERSION }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "changes:\n ${{ env.COMMIT_MSGS }}"
